In [9]:
import numpy as np
a=([1,2,3],[1,3,4])
b=np.array(a)
for i in b:
    print(i)

[1 2 3]
[1 3 4]


In [36]:
#convert float aarays into int array
a=list(input('enter l1:'))
#b=list(input('enter l2:'))
flt_lst1=[float(i) for i in a]
#flt_lst2=[float(j) for j in b]
flt_array=np.array((flt_lst1)) #,flt_lst2))
#flt_array
flt_array.astype(int)

enter l1:123


array([1, 2, 3])

In [35]:
a=list(input('enter r1 for a1:'))
b=list(input('enter r2 for a1:'))
array1=np.array((a,b))
c=list(input('enter r1 for a2:'))
d=list(input('enter r2 for a2:'))
array2=np.array((c,d))
print('array1: ', array1)
print('array2: ', array2)



enter r1 for a1:12
enter r2 for a1:45
enter r1 for a2:78
enter r2 for a2:96
array1:  [['1' '2']
 ['4' '5']]
array2:  [['7' '8']
 ['9' '6']]


In [60]:
a=list(input('a1: '))
b=list(input('a2: '))
int_a=[int(i) for i in a]
int_b=[int(i) for i in b]
array1=np.array(int_a)
array2=np.array(int_b)
print('array1= ', array1)
print('array2= ', array2)
c=0
if np.size(array1)!= np.size(array2):
    print('Arrays are not equal')
else:
    for i in array1:
        if array1[i-1]!=array2[i-1]:
            print('arrays are not equal')
            c=1
            break
    if c==0:
        print('arrays are equal')
        

a1: 123
a2: 123
array1=  [1 2 3]
array2=  [1 2 3]
arrays are equal


In [110]:
import math
a=np.random.random((10,2))
print('input: ', a)
p=[]
for i in range(10):
    r=math.sqrt((a[i,0]*a[i,0])+(a[i,1]*a[i,1]))
    Q=math.atan(a[i,1]/a[i,0])
    p.append((r,Q))

b=np.array(p)
c=np.reshape(b,(10,2))
print('output: ',c)

input:  [[0.93491532 0.56783166]
 [0.99882053 0.70571772]
 [0.09636284 0.37073078]
 [0.63674007 0.99208224]
 [0.66449511 0.10471313]
 [0.77290403 0.38420291]
 [0.26961538 0.39257816]
 [0.67393041 0.88664077]
 [0.52502411 0.31434701]
 [0.04270106 0.38389046]]
output:  [[1.09384618 0.54581486]
 [1.22297995 0.61510914]
 [0.38304974 1.3164969 ]
 [1.17884057 1.00019174]
 [0.67269503 0.15629771]
 [0.86312949 0.46131695]
 [0.4762458  0.96899711]
 [1.11369388 0.92086624]
 [0.61193493 0.5394842 ]
 [0.38625803 1.46001929]]
